package FFUTF;

# 2006_09_24 -- pfs -- initial version
# 2006_09_24 -- entities2UTF8 routine
#2006_11_26 -- maybe special treatment for &nbsp; or it disappears
#2007_05_27 -- add basic idiomatic flatLatin -- oe, ae, etc.
#2007_05_27 -- allow - and . in safe names
#2007_05_28 -- make allowing punctuation optional
#2011_09_01 -- RETURN IF NO UNFLAT LATIN TO CONVERT
#2014_07_17 -- routine to convert all entities to utf-8, then return flat latin

use 5.008003;	# I'm using 5.8.3 to develop this
use strict;
no strict 'refs';
use vars qw{@ISA @EXPORT @EXPORT_OK %EXPORT_TAGS $VERSION };

use Exporter;
$VERSION = 0.01;		# pfs -- 2006_06_12 -- initial version

@ISA = qw{Exporter};
@EXPORT_OK = qw{entities2UTF8 toLatinSafe};

use utf8;	# all strings here to be treated as UTF-8
use HTML::Entities;	# for entity conversion hash

#GLOBALS 
#$ret = $toCaronized{$toBeModified} if $toCaronized{$toBeModified};
my %toCaronized = ();

my %decoratedLatinToFlat = (

  'A' => 'A', # 0065 0041 LATIN CAPITAL LETTER A
  'B' => 'B', # 0066 0042 LATIN CAPITAL LETTER B
  'C' => 'C', # 0067 0043 LATIN CAPITAL LETTER C
  'D' => 'D', # 0068 0044 LATIN CAPITAL LETTER D
  'E' => 'E', # 0069 0045 LATIN CAPITAL LETTER E
  'F' => 'F', # 0070 0046 LATIN CAPITAL LETTER F
  'G' => 'G', # 0071 0047 LATIN CAPITAL LETTER G
  'H' => 'H', # 0072 0048 LATIN CAPITAL LETTER H
  'I' => 'I', # 0073 0049 LATIN CAPITAL LETTER I
  'J' => 'J', # 0074 004A LATIN CAPITAL LETTER J
  'K' => 'K', # 0075 004B LATIN CAPITAL LETTER K
  'L' => 'L', # 0076 004C LATIN CAPITAL LETTER L
  'M' => 'M', # 0077 004D LATIN CAPITAL LETTER M
  'N' => 'N', # 0078 004E LATIN CAPITAL LETTER N
  'O' => 'O', # 0079 004F LATIN CAPITAL LETTER O
  'P' => 'P', # 0080 0050 LATIN CAPITAL LETTER P
  'Q' => 'Q', # 0081 0051 LATIN CAPITAL LETTER Q
  'R' => 'R', # 0082 0052 LATIN CAPITAL LETTER R
  'S' => 'S', # 0083 0053 LATIN CAPITAL LETTER S
  'T' => 'T', # 0084 0054 LATIN CAPITAL LETTER T
  'U' => 'U', # 0085 0055 LATIN CAPITAL LETTER U
  'V' => 'V', # 0086 0056 LATIN CAPITAL LETTER V
  'W' => 'W', # 0087 0057 LATIN CAPITAL LETTER W
  'X' => 'X', # 0088 0058 LATIN CAPITAL LETTER X
  'Y' => 'Y', # 0089 0059 LATIN CAPITAL LETTER Y
  'Z' => 'Z', # 0090 005A LATIN CAPITAL LETTER Z
  'a' => 'a', # 0097 0061 LATIN SMALL LETTER A
  'b' => 'b', # 0098 0062 LATIN SMALL LETTER B
  'c' => 'c', # 0099 0063 LATIN SMALL LETTER C
  'd' => 'd', # 0100 0064 LATIN SMALL LETTER D
  'e' => 'e', # 0101 0065 LATIN SMALL LETTER E
  'f' => 'f', # 0102 0066 LATIN SMALL LETTER F
  'g' => 'g', # 0103 0067 LATIN SMALL LETTER G
  'h' => 'h', # 0104 0068 LATIN SMALL LETTER H
  'i' => 'i', # 0105 0069 LATIN SMALL LETTER I
  'j' => 'j', # 0106 006A LATIN SMALL LETTER J
  'k' => 'k', # 0107 006B LATIN SMALL LETTER K
  'l' => 'l', # 0108 006C LATIN SMALL LETTER L
  'm' => 'm', # 0109 006D LATIN SMALL LETTER M
  'n' => 'n', # 0110 006E LATIN SMALL LETTER N
  'o' => 'o', # 0111 006F LATIN SMALL LETTER O
  'p' => 'p', # 0112 0070 LATIN SMALL LETTER P
  'q' => 'q', # 0113 0071 LATIN SMALL LETTER Q
  'r' => 'r', # 0114 0072 LATIN SMALL LETTER R
  's' => 's', # 0115 0073 LATIN SMALL LETTER S
  't' => 't', # 0116 0074 LATIN SMALL LETTER T
  'u' => 'u', # 0117 0075 LATIN SMALL LETTER U
  'v' => 'v', # 0118 0076 LATIN SMALL LETTER V
  'w' => 'w', # 0119 0077 LATIN SMALL LETTER W
  'x' => 'x', # 0120 0078 LATIN SMALL LETTER X
  'y' => 'y', # 0121 0079 LATIN SMALL LETTER Y
  'z' => 'z', # 0122 007A LATIN SMALL LETTER Z
  'À' => 'A', # 0192 00C0 LATIN CAPITAL LETTER A WITH GRAVE
  'Á' => 'A', # 0193 00C1 LATIN CAPITAL LETTER A WITH ACUTE
  'Â' => 'A', # 0194 00C2 LATIN CAPITAL LETTER A WITH CIRCUMFLEX
  'Ã' => 'A', # 0195 00C3 LATIN CAPITAL LETTER A WITH TILDE
  'Ä' => 'A', # 0196 00C4 LATIN CAPITAL LETTER A WITH DIAERESIS
  'Å' => 'A', # 0197 00C5 LATIN CAPITAL LETTER A WITH RING ABOVE
  'Æ' => 'AE', # 0198 00C6 LATIN CAPITAL LETTER AE
  'Ç' => 'C', # 0199 00C7 LATIN CAPITAL LETTER C WITH CEDILLA
  'È' => 'E', # 0200 00C8 LATIN CAPITAL LETTER E WITH GRAVE
  'É' => 'E', # 0201 00C9 LATIN CAPITAL LETTER E WITH ACUTE
  'Ê' => 'E', # 0202 00CA LATIN CAPITAL LETTER E WITH CIRCUMFLEX
  'Ë' => 'E', # 0203 00CB LATIN CAPITAL LETTER E WITH DIAERESIS
  'Ì' => 'I', # 0204 00CC LATIN CAPITAL LETTER I WITH GRAVE
  'Í' => 'I', # 0205 00CD LATIN CAPITAL LETTER I WITH ACUTE
  'Î' => 'I', # 0206 00CE LATIN CAPITAL LETTER I WITH CIRCUMFLEX
  'Ï' => 'I', # 0207 00CF LATIN CAPITAL LETTER I WITH DIAERESIS
  'Ñ' => 'N', # 0209 00D1 LATIN CAPITAL LETTER N WITH TILDE
  'Ò' => 'O', # 0210 00D2 LATIN CAPITAL LETTER O WITH GRAVE
  'Ó' => 'O', # 0211 00D3 LATIN CAPITAL LETTER O WITH ACUTE
  'Ô' => 'O', # 0212 00D4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX
  'Õ' => 'O', # 0213 00D5 LATIN CAPITAL LETTER O WITH TILDE
  'Ö' => 'O', # 0214 00D6 LATIN CAPITAL LETTER O WITH DIAERESIS
  'Ø' => 'O', # 0216 00D8 LATIN CAPITAL LETTER O WITH STROKE
  'Ù' => 'U', # 0217 00D9 LATIN CAPITAL LETTER U WITH GRAVE
  'Ú' => 'U', # 0218 00DA LATIN CAPITAL LETTER U WITH ACUTE
  'Û' => 'U', # 0219 00DB LATIN CAPITAL LETTER U WITH CIRCUMFLEX
  'Ü' => 'U', # 0220 00DC LATIN CAPITAL LETTER U WITH DIAERESIS
  'Ý' => 'Y', # 0221 00DD LATIN CAPITAL LETTER Y WITH ACUTE
  'à' => 'a', # 0224 00E0 LATIN SMALL LETTER A WITH GRAVE
  'á' => 'a', # 0225 00E1 LATIN SMALL LETTER A WITH ACUTE
  'â' => 'a', # 0226 00E2 LATIN SMALL LETTER A WITH CIRCUMFLEX
  'ã' => 'a', # 0227 00E3 LATIN SMALL LETTER A WITH TILDE
  'ä' => 'a', # 0228 00E4 LATIN SMALL LETTER A WITH DIAERESIS
  'å' => 'a', # 0229 00E5 LATIN SMALL LETTER A WITH RING ABOVE
  'æ' => 'ae', # 0230 00E6 LATIN SMALL LETTER AE
  'ç' => 'c', # 0231 00E7 LATIN SMALL LETTER C WITH CEDILLA
  'è' => 'e', # 0232 00E8 LATIN SMALL LETTER E WITH GRAVE
  'é' => 'e', # 0233 00E9 LATIN SMALL LETTER E WITH ACUTE
  'ê' => 'e', # 0234 00EA LATIN SMALL LETTER E WITH CIRCUMFLEX
  'ë' => 'e', # 0235 00EB LATIN SMALL LETTER E WITH DIAERESIS
  'ì' => 'i', # 0236 00EC LATIN SMALL LETTER I WITH GRAVE
  'í' => 'i', # 0237 00ED LATIN SMALL LETTER I WITH ACUTE
  'î' => 'i', # 0238 00EE LATIN SMALL LETTER I WITH CIRCUMFLEX
  'ï' => 'i', # 0239 00EF LATIN SMALL LETTER I WITH DIAERESIS
  'ñ' => 'n', # 0241 00F1 LATIN SMALL LETTER N WITH TILDE
  'ò' => 'o', # 0242 00F2 LATIN SMALL LETTER O WITH GRAVE
  'ó' => 'o', # 0243 00F3 LATIN SMALL LETTER O WITH ACUTE
  'ô' => 'o', # 0244 00F4 LATIN SMALL LETTER O WITH CIRCUMFLEX
  'õ' => 'o', # 0245 00F5 LATIN SMALL LETTER O WITH TILDE
  'ö' => 'o', # 0246 00F6 LATIN SMALL LETTER O WITH DIAERESIS
  'ø' => 'o', # 0248 00F8 LATIN SMALL LETTER O WITH STROKE
  'ù' => 'u', # 0249 00F9 LATIN SMALL LETTER U WITH GRAVE
  'ú' => 'u', # 0250 00FA LATIN SMALL LETTER U WITH ACUTE
  'û' => 'u', # 0251 00FB LATIN SMALL LETTER U WITH CIRCUMFLEX
  'ü' => 'u', # 0252 00FC LATIN SMALL LETTER U WITH DIAERESIS
  'ý' => 'y', # 0253 00FD LATIN SMALL LETTER Y WITH ACUTE
  'ÿ' => 'y', # 0255 00FF LATIN SMALL LETTER Y WITH DIAERESIS
  'Ā' => 'A', # 0256 0100 LATIN CAPITAL LETTER A WITH MACRON
  'ā' => 'a', # 0257 0101 LATIN SMALL LETTER A WITH MACRON
  'Ă' => 'A', # 0258 0102 LATIN CAPITAL LETTER A WITH BREVE
  'ă' => 'a', # 0259 0103 LATIN SMALL LETTER A WITH BREVE
  'Ą' => 'A', # 0260 0104 LATIN CAPITAL LETTER A WITH OGONEK
  'ą' => 'a', # 0261 0105 LATIN SMALL LETTER A WITH OGONEK
  'Ć' => 'C', # 0262 0106 LATIN CAPITAL LETTER C WITH ACUTE
  'ć' => 'c', # 0263 0107 LATIN SMALL LETTER C WITH ACUTE
  'Ĉ' => 'C', # 0264 0108 LATIN CAPITAL LETTER C WITH CIRCUMFLEX
  'ĉ' => 'c', # 0265 0109 LATIN SMALL LETTER C WITH CIRCUMFLEX
  'Ċ' => 'C', # 0266 010A LATIN CAPITAL LETTER C WITH DOT ABOVE
  'ċ' => 'c', # 0267 010B LATIN SMALL LETTER C WITH DOT ABOVE
  'Č' => 'C', # 0268 010C LATIN CAPITAL LETTER C WITH CARON
  'č' => 'c', # 0269 010D LATIN SMALL LETTER C WITH CARON
  'Ď' => 'D', # 0270 010E LATIN CAPITAL LETTER D WITH CARON
  'ď' => 'd', # 0271 010F LATIN SMALL LETTER D WITH CARON
  'Đ' => 'D', # 0272 0110 LATIN CAPITAL LETTER D WITH STROKE
  'đ' => 'd', # 0273 0111 LATIN SMALL LETTER D WITH STROKE
  'Ē' => 'E', # 0274 0112 LATIN CAPITAL LETTER E WITH MACRON
  'ē' => 'e', # 0275 0113 LATIN SMALL LETTER E WITH MACRON
  'Ĕ' => 'E', # 0276 0114 LATIN CAPITAL LETTER E WITH BREVE
  'ĕ' => 'e', # 0277 0115 LATIN SMALL LETTER E WITH BREVE
  'Ė' => 'E', # 0278 0116 LATIN CAPITAL LETTER E WITH DOT ABOVE
  'ė' => 'e', # 0279 0117 LATIN SMALL LETTER E WITH DOT ABOVE
  'Ę' => 'E', # 0280 0118 LATIN CAPITAL LETTER E WITH OGONEK
  'ę' => 'e', # 0281 0119 LATIN SMALL LETTER E WITH OGONEK
  'Ě' => 'E', # 0282 011A LATIN CAPITAL LETTER E WITH CARON
  'ě' => 'e', # 0283 011B LATIN SMALL LETTER E WITH CARON
  'Ĝ' => 'G', # 0284 011C LATIN CAPITAL LETTER G WITH CIRCUMFLEX
  'ĝ' => 'g', # 0285 011D LATIN SMALL LETTER G WITH CIRCUMFLEX
  'Ğ' => 'G', # 0286 011E LATIN CAPITAL LETTER G WITH BREVE
  'ğ' => 'g', # 0287 011F LATIN SMALL LETTER G WITH BREVE
  'Ġ' => 'G', # 0288 0120 LATIN CAPITAL LETTER G WITH DOT ABOVE
  'ġ' => 'g', # 0289 0121 LATIN SMALL LETTER G WITH DOT ABOVE
  'Ģ' => 'G', # 0290 0122 LATIN CAPITAL LETTER G WITH CEDILLA
  'ģ' => 'g', # 0291 0123 LATIN SMALL LETTER G WITH CEDILLA
  'Ĥ' => 'H', # 0292 0124 LATIN CAPITAL LETTER H WITH CIRCUMFLEX
  'ĥ' => 'h', # 0293 0125 LATIN SMALL LETTER H WITH CIRCUMFLEX
  'Ħ' => 'H', # 0294 0126 LATIN CAPITAL LETTER H WITH STROKE
  'ħ' => 'h', # 0295 0127 LATIN SMALL LETTER H WITH STROKE
  'Ĩ' => 'I', # 0296 0128 LATIN CAPITAL LETTER I WITH TILDE
  'ĩ' => 'i', # 0297 0129 LATIN SMALL LETTER I WITH TILDE
  'Ī' => 'I', # 0298 012A LATIN CAPITAL LETTER I WITH MACRON
  'ī' => 'i', # 0299 012B LATIN SMALL LETTER I WITH MACRON
  'Ĭ' => 'I', # 0300 012C LATIN CAPITAL LETTER I WITH BREVE
  'ĭ' => 'i', # 0301 012D LATIN SMALL LETTER I WITH BREVE
  'Į' => 'I', # 0302 012E LATIN CAPITAL LETTER I WITH OGONEK
  'į' => 'i', # 0303 012F LATIN SMALL LETTER I WITH OGONEK
  'İ' => 'I', # 0304 0130 LATIN CAPITAL LETTER I WITH DOT ABOVE
  'Ĵ' => 'J', # 0308 0134 LATIN CAPITAL LETTER J WITH CIRCUMFLEX
  'ĵ' => 'j', # 0309 0135 LATIN SMALL LETTER J WITH CIRCUMFLEX
  'Ķ' => 'K', # 0310 0136 LATIN CAPITAL LETTER K WITH CEDILLA
  'ķ' => 'k', # 0311 0137 LATIN SMALL LETTER K WITH CEDILLA
  'Ĺ' => 'L', # 0313 0139 LATIN CAPITAL LETTER L WITH ACUTE
  'ĺ' => 'l', # 0314 013A LATIN SMALL LETTER L WITH ACUTE
  'Ļ' => 'L', # 0315 013B LATIN CAPITAL LETTER L WITH CEDILLA
  'ļ' => 'l', # 0316 013C LATIN SMALL LETTER L WITH CEDILLA
  'Ľ' => 'L', # 0317 013D LATIN CAPITAL LETTER L WITH CARON
  'ľ' => 'l', # 0318 013E LATIN SMALL LETTER L WITH CARON
  'Ŀ' => 'L', # 0319 013F LATIN CAPITAL LETTER L WITH MIDDLE DOT
  'ŀ' => 'l', # 0320 0140 LATIN SMALL LETTER L WITH MIDDLE DOT
  'Ł' => 'L', # 0321 0141 LATIN CAPITAL LETTER L WITH STROKE
  'ł' => 'l', # 0322 0142 LATIN SMALL LETTER L WITH STROKE
  'Ń' => 'N', # 0323 0143 LATIN CAPITAL LETTER N WITH ACUTE
  'ń' => 'n', # 0324 0144 LATIN SMALL LETTER N WITH ACUTE
  'Ņ' => 'N', # 0325 0145 LATIN CAPITAL LETTER N WITH CEDILLA
  'ņ' => 'n', # 0326 0146 LATIN SMALL LETTER N WITH CEDILLA
  'Ň' => 'N', # 0327 0147 LATIN CAPITAL LETTER N WITH CARON
  'ň' => 'n', # 0328 0148 LATIN SMALL LETTER N WITH CARON
  'Ō' => 'O', # 0332 014C LATIN CAPITAL LETTER O WITH MACRON
  'ō' => 'o', # 0333 014D LATIN SMALL LETTER O WITH MACRON
  'Ŏ' => 'O', # 0334 014E LATIN CAPITAL LETTER O WITH BREVE
  'ŏ' => 'o', # 0335 014F LATIN SMALL LETTER O WITH BREVE
  'Ő' => 'O', # 0336 0150 LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
  'ő' => 'o', # 0337 0151 LATIN SMALL LETTER O WITH DOUBLE ACUTE
  'Ŕ' => 'R', # 0340 0154 LATIN CAPITAL LETTER R WITH ACUTE
  'ŕ' => 'r', # 0341 0155 LATIN SMALL LETTER R WITH ACUTE
  'Ŗ' => 'R', # 0342 0156 LATIN CAPITAL LETTER R WITH CEDILLA
  'ŗ' => 'r', # 0343 0157 LATIN SMALL LETTER R WITH CEDILLA
  'Ř' => 'R', # 0344 0158 LATIN CAPITAL LETTER R WITH CARON
  'ř' => 'r', # 0345 0159 LATIN SMALL LETTER R WITH CARON
  'Ś' => 'S', # 0346 015A LATIN CAPITAL LETTER S WITH ACUTE
  'ś' => 's', # 0347 015B LATIN SMALL LETTER S WITH ACUTE
  'Ŝ' => 'S', # 0348 015C LATIN CAPITAL LETTER S WITH CIRCUMFLEX
  'ŝ' => 's', # 0349 015D LATIN SMALL LETTER S WITH CIRCUMFLEX
  'Ş' => 'S', # 0350 015E LATIN CAPITAL LETTER S WITH CEDILLA
  'ş' => 's', # 0351 015F LATIN SMALL LETTER S WITH CEDILLA
  'Š' => 'S', # 0352 0160 LATIN CAPITAL LETTER S WITH CARON
  'š' => 's', # 0353 0161 LATIN SMALL LETTER S WITH CARON
  'Ţ' => 'T', # 0354 0162 LATIN CAPITAL LETTER T WITH CEDILLA
  'ţ' => 't', # 0355 0163 LATIN SMALL LETTER T WITH CEDILLA
  'Ť' => 'T', # 0356 0164 LATIN CAPITAL LETTER T WITH CARON
  'ť' => 't', # 0357 0165 LATIN SMALL LETTER T WITH CARON
  'Ŧ' => 'T', # 0358 0166 LATIN CAPITAL LETTER T WITH STROKE
  'ŧ' => 't', # 0359 0167 LATIN SMALL LETTER T WITH STROKE
  'Ũ' => 'U', # 0360 0168 LATIN CAPITAL LETTER U WITH TILDE
  'ũ' => 'u', # 0361 0169 LATIN SMALL LETTER U WITH TILDE
  'Ū' => 'U', # 0362 016A LATIN CAPITAL LETTER U WITH MACRON
  'ū' => 'u', # 0363 016B LATIN SMALL LETTER U WITH MACRON
  'Ŭ' => 'U', # 0364 016C LATIN CAPITAL LETTER U WITH BREVE
  'ŭ' => 'u', # 0365 016D LATIN SMALL LETTER U WITH BREVE
  'Ů' => 'U', # 0366 016E LATIN CAPITAL LETTER U WITH RING ABOVE
  'ů' => 'u', # 0367 016F LATIN SMALL LETTER U WITH RING ABOVE
  'Ű' => 'U', # 0368 0170 LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
  'ű' => 'u', # 0369 0171 LATIN SMALL LETTER U WITH DOUBLE ACUTE
  'Ų' => 'U', # 0370 0172 LATIN CAPITAL LETTER U WITH OGONEK
  'ų' => 'u', # 0371 0173 LATIN SMALL LETTER U WITH OGONEK
  'Ŵ' => 'W', # 0372 0174 LATIN CAPITAL LETTER W WITH CIRCUMFLEX
  'ŵ' => 'w', # 0373 0175 LATIN SMALL LETTER W WITH CIRCUMFLEX
  'Ŷ' => 'Y', # 0374 0176 LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
  'ŷ' => 'y', # 0375 0177 LATIN SMALL LETTER Y WITH CIRCUMFLEX
  'Ÿ' => 'Y', # 0376 0178 LATIN CAPITAL LETTER Y WITH DIAERESIS
  'Ź' => 'Z', # 0377 0179 LATIN CAPITAL LETTER Z WITH ACUTE
  'ź' => 'z', # 0378 017A LATIN SMALL LETTER Z WITH ACUTE
  'Ż' => 'Z', # 0379 017B LATIN CAPITAL LETTER Z WITH DOT ABOVE
  'ż' => 'z', # 0380 017C LATIN SMALL LETTER Z WITH DOT ABOVE
  'Ž' => 'Z', # 0381 017D LATIN CAPITAL LETTER Z WITH CARON
  'ž' => 'z', # 0382 017E LATIN SMALL LETTER Z WITH CARON
  'ƀ' => 'b', # 0384 0180 LATIN SMALL LETTER B WITH STROKE
  'Ɓ' => 'B', # 0385 0181 LATIN CAPITAL LETTER B WITH HOOK
  'Ƃ' => 'B', # 0386 0182 LATIN CAPITAL LETTER B WITH TOPBAR
  'ƃ' => 'b', # 0387 0183 LATIN SMALL LETTER B WITH TOPBAR
  'Ƈ' => 'C', # 0391 0187 LATIN CAPITAL LETTER C WITH HOOK
  'ƈ' => 'c', # 0392 0188 LATIN SMALL LETTER C WITH HOOK
  'Ɗ' => 'D', # 0394 018A LATIN CAPITAL LETTER D WITH HOOK
  'Ƌ' => 'D', # 0395 018B LATIN CAPITAL LETTER D WITH TOPBAR
  'ƌ' => 'd', # 0396 018C LATIN SMALL LETTER D WITH TOPBAR
  'Ƒ' => 'F', # 0401 0191 LATIN CAPITAL LETTER F WITH HOOK
  'ƒ' => 'f', # 0402 0192 LATIN SMALL LETTER F WITH HOOK
  'Ɠ' => 'G', # 0403 0193 LATIN CAPITAL LETTER G WITH HOOK
  'ƕ' => 'hv', # 0405 0195 LATIN SMALL LETTER HV
  'Ɨ' => 'I', # 0407 0197 LATIN CAPITAL LETTER I WITH STROKE
  'Ƙ' => 'K', # 0408 0198 LATIN CAPITAL LETTER K WITH HOOK
  'ƙ' => 'k', # 0409 0199 LATIN SMALL LETTER K WITH HOOK
  'ƚ' => 'l', # 0410 019A LATIN SMALL LETTER L WITH BAR
  'Ɲ' => 'N', # 0413 019D LATIN CAPITAL LETTER N WITH LEFT HOOK
  'ƞ' => 'n', # 0414 019E LATIN SMALL LETTER N WITH LONG RIGHT LEG
  'Ɵ' => 'O', # 0415 019F LATIN CAPITAL LETTER O WITH MIDDLE TILDE
  'Ơ' => 'O', # 0416 01A0 LATIN CAPITAL LETTER O WITH HORN
  'ơ' => 'o', # 0417 01A1 LATIN SMALL LETTER O WITH HORN
  'Ƣ' => 'OI', # 0418 01A2 LATIN CAPITAL LETTER OI
  'ƣ' => 'oi', # 0419 01A3 LATIN SMALL LETTER OI
  'Ƥ' => 'P', # 0420 01A4 LATIN CAPITAL LETTER P WITH HOOK
  'ƥ' => 'p', # 0421 01A5 LATIN SMALL LETTER P WITH HOOK
  'ƫ' => 't', # 0427 01AB LATIN SMALL LETTER T WITH PALATAL HOOK
  'Ƭ' => 'T', # 0428 01AC LATIN CAPITAL LETTER T WITH HOOK
  'ƭ' => 't', # 0429 01AD LATIN SMALL LETTER T WITH HOOK
  'Ʈ' => 'T', # 0430 01AE LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
  'Ư' => 'U', # 0431 01AF LATIN CAPITAL LETTER U WITH HORN
  'ư' => 'u', # 0432 01B0 LATIN SMALL LETTER U WITH HORN
  'Ʋ' => 'V', # 0434 01B2 LATIN CAPITAL LETTER V WITH HOOK
  'Ƴ' => 'Y', # 0435 01B3 LATIN CAPITAL LETTER Y WITH HOOK
  'ƴ' => 'y', # 0436 01B4 LATIN SMALL LETTER Y WITH HOOK
  'Ƶ' => 'Z', # 0437 01B5 LATIN CAPITAL LETTER Z WITH STROKE
  'ƶ' => 'z', # 0438 01B6 LATIN SMALL LETTER Z WITH STROKE
  'Ǆ' => 'DZ', # 0452 01C4 LATIN CAPITAL LETTER DZ WITH CARON
  'ǅ' => 'D', # 0453 01C5 LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
  'ǆ' => 'dz', # 0454 01C6 LATIN SMALL LETTER DZ WITH CARON
  'Ǉ' => 'LJ', # 0455 01C7 LATIN CAPITAL LETTER LJ
  'ǈ' => 'L', # 0456 01C8 LATIN CAPITAL LETTER L WITH SMALL LETTER J
  'ǉ' => 'lj', # 0457 01C9 LATIN SMALL LETTER LJ
  'Ǌ' => 'NJ', # 0458 01CA LATIN CAPITAL LETTER NJ
  'ǋ' => 'N', # 0459 01CB LATIN CAPITAL LETTER N WITH SMALL LETTER J
  'ǌ' => 'nj', # 0460 01CC LATIN SMALL LETTER NJ
  'Ǎ' => 'A', # 0461 01CD LATIN CAPITAL LETTER A WITH CARON
  'ǎ' => 'a', # 0462 01CE LATIN SMALL LETTER A WITH CARON
  'Ǐ' => 'I', # 0463 01CF LATIN CAPITAL LETTER I WITH CARON
  'ǐ' => 'i', # 0464 01D0 LATIN SMALL LETTER I WITH CARON
  'Ǒ' => 'O', # 0465 01D1 LATIN CAPITAL LETTER O WITH CARON
  'ǒ' => 'o', # 0466 01D2 LATIN SMALL LETTER O WITH CARON
  'Ǔ' => 'U', # 0467 01D3 LATIN CAPITAL LETTER U WITH CARON
  'ǔ' => 'u', # 0468 01D4 LATIN SMALL LETTER U WITH CARON
  'Ǖ' => 'U', # 0469 01D5 LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
  'ǖ' => 'u', # 0470 01D6 LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
  'Ǘ' => 'U', # 0471 01D7 LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
  'ǘ' => 'u', # 0472 01D8 LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
  'Ǚ' => 'U', # 0473 01D9 LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
  'ǚ' => 'u', # 0474 01DA LATIN SMALL LETTER U WITH DIAERESIS AND CARON
  'Ǜ' => 'U', # 0475 01DB LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
  'ǜ' => 'u', # 0476 01DC LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
  'Ǟ' => 'A', # 0478 01DE LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
  'ǟ' => 'a', # 0479 01DF LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
  'Ǡ' => 'A', # 0480 01E0 LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
  'ǡ' => 'a', # 0481 01E1 LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
  'Ǣ' => 'AE', # 0482 01E2 LATIN CAPITAL LETTER AE WITH MACRON
  'ǣ' => 'ae', # 0483 01E3 LATIN SMALL LETTER AE WITH MACRON
  'Ǥ' => 'G', # 0484 01E4 LATIN CAPITAL LETTER G WITH STROKE
  'ǥ' => 'g', # 0485 01E5 LATIN SMALL LETTER G WITH STROKE
  'Ǧ' => 'G', # 0486 01E6 LATIN CAPITAL LETTER G WITH CARON
  'ǧ' => 'g', # 0487 01E7 LATIN SMALL LETTER G WITH CARON
  'Ǩ' => 'K', # 0488 01E8 LATIN CAPITAL LETTER K WITH CARON
  'ǩ' => 'k', # 0489 01E9 LATIN SMALL LETTER K WITH CARON
  'Ǫ' => 'O', # 0490 01EA LATIN CAPITAL LETTER O WITH OGONEK
  'ǫ' => 'o', # 0491 01EB LATIN SMALL LETTER O WITH OGONEK
  'Ǭ' => 'O', # 0492 01EC LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
  'ǭ' => 'o', # 0493 01ED LATIN SMALL LETTER O WITH OGONEK AND MACRON
  'ǰ' => 'j', # 0496 01F0 LATIN SMALL LETTER J WITH CARON
  'Ǳ' => 'DZ', # 0497 01F1 LATIN CAPITAL LETTER DZ
  'ǲ' => 'D', # 0498 01F2 LATIN CAPITAL LETTER D WITH SMALL LETTER Z
  'ǳ' => 'dz', # 0499 01F3 LATIN SMALL LETTER DZ
  'Ǵ' => 'G', # 0500 01F4 LATIN CAPITAL LETTER G WITH ACUTE
  'ǵ' => 'g', # 0501 01F5 LATIN SMALL LETTER G WITH ACUTE
  'Ǹ' => 'N', # 0504 01F8 LATIN CAPITAL LETTER N WITH GRAVE
  'ǹ' => 'n', # 0505 01F9 LATIN SMALL LETTER N WITH GRAVE
  'Ǻ' => 'A', # 0506 01FA LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
  'ǻ' => 'a', # 0507 01FB LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
  'Ǽ' => 'AE', # 0508 01FC LATIN CAPITAL LETTER AE WITH ACUTE
  'ǽ' => 'ae', # 0509 01FD LATIN SMALL LETTER AE WITH ACUTE
  'Ǿ' => 'O', # 0510 01FE LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
  'ǿ' => 'o', # 0511 01FF LATIN SMALL LETTER O WITH STROKE AND ACUTE
  'Ȁ' => 'A', # 0512 0200 LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
  'ȁ' => 'a', # 0513 0201 LATIN SMALL LETTER A WITH DOUBLE GRAVE
  'Ȃ' => 'A', # 0514 0202 LATIN CAPITAL LETTER A WITH INVERTED BREVE
  'ȃ' => 'a', # 0515 0203 LATIN SMALL LETTER A WITH INVERTED BREVE
  'Ȅ' => 'E', # 0516 0204 LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
  'ȅ' => 'e', # 0517 0205 LATIN SMALL LETTER E WITH DOUBLE GRAVE
  'Ȇ' => 'E', # 0518 0206 LATIN CAPITAL LETTER E WITH INVERTED BREVE
  'ȇ' => 'e', # 0519 0207 LATIN SMALL LETTER E WITH INVERTED BREVE
  'Ȉ' => 'I', # 0520 0208 LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
  'ȉ' => 'i', # 0521 0209 LATIN SMALL LETTER I WITH DOUBLE GRAVE
  'Ȋ' => 'I', # 0522 020A LATIN CAPITAL LETTER I WITH INVERTED BREVE
  'ȋ' => 'i', # 0523 020B LATIN SMALL LETTER I WITH INVERTED BREVE
  'Ȍ' => 'O', # 0524 020C LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
  'ȍ' => 'o', # 0525 020D LATIN SMALL LETTER O WITH DOUBLE GRAVE
  'Ȏ' => 'O', # 0526 020E LATIN CAPITAL LETTER O WITH INVERTED BREVE
  'ȏ' => 'o', # 0527 020F LATIN SMALL LETTER O WITH INVERTED BREVE
  'Ȑ' => 'R', # 0528 0210 LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
  'ȑ' => 'r', # 0529 0211 LATIN SMALL LETTER R WITH DOUBLE GRAVE
  'Ȓ' => 'R', # 0530 0212 LATIN CAPITAL LETTER R WITH INVERTED BREVE
  'ȓ' => 'r', # 0531 0213 LATIN SMALL LETTER R WITH INVERTED BREVE
  'Ȕ' => 'U', # 0532 0214 LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
  'ȕ' => 'u', # 0533 0215 LATIN SMALL LETTER U WITH DOUBLE GRAVE
  'Ȗ' => 'U', # 0534 0216 LATIN CAPITAL LETTER U WITH INVERTED BREVE
  'ȗ' => 'u', # 0535 0217 LATIN SMALL LETTER U WITH INVERTED BREVE
  'Ș' => 'S', # 0536 0218 LATIN CAPITAL LETTER S WITH COMMA BELOW
  'ș' => 's', # 0537 0219 LATIN SMALL LETTER S WITH COMMA BELOW
  'Ț' => 'T', # 0538 021A LATIN CAPITAL LETTER T WITH COMMA BELOW
  'ț' => 't', # 0539 021B LATIN SMALL LETTER T WITH COMMA BELOW
  'Ȟ' => 'H', # 0542 021E LATIN CAPITAL LETTER H WITH CARON
  'ȟ' => 'h', # 0543 021F LATIN SMALL LETTER H WITH CARON
  'Ƞ' => 'N', # 0544 0220 LATIN CAPITAL LETTER N WITH LONG RIGHT LEG
  'ȡ' => 'd', # 0545 0221 LATIN SMALL LETTER D WITH CURL
  'Ȣ' => 'OU', # 0546 0222 LATIN CAPITAL LETTER OU
  'ȣ' => 'ou', # 0547 0223 LATIN SMALL LETTER OU
  'Ȥ' => 'Z', # 0548 0224 LATIN CAPITAL LETTER Z WITH HOOK
  'ȥ' => 'z', # 0549 0225 LATIN SMALL LETTER Z WITH HOOK
  'Ȧ' => 'A', # 0550 0226 LATIN CAPITAL LETTER A WITH DOT ABOVE
  'ȧ' => 'a', # 0551 0227 LATIN SMALL LETTER A WITH DOT ABOVE
  'Ȩ' => 'E', # 0552 0228 LATIN CAPITAL LETTER E WITH CEDILLA
  'ȩ' => 'e', # 0553 0229 LATIN SMALL LETTER E WITH CEDILLA
  'Ȫ' => 'O', # 0554 022A LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
  'ȫ' => 'o', # 0555 022B LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
  'Ȭ' => 'O', # 0556 022C LATIN CAPITAL LETTER O WITH TILDE AND MACRON
  'ȭ' => 'o', # 0557 022D LATIN SMALL LETTER O WITH TILDE AND MACRON
  'Ȯ' => 'O', # 0558 022E LATIN CAPITAL LETTER O WITH DOT ABOVE
  'ȯ' => 'o', # 0559 022F LATIN SMALL LETTER O WITH DOT ABOVE
  'Ȱ' => 'O', # 0560 0230 LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
  'ȱ' => 'o', # 0561 0231 LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
  'Ȳ' => 'Y', # 0562 0232 LATIN CAPITAL LETTER Y WITH MACRON
  'ȳ' => 'y', # 0563 0233 LATIN SMALL LETTER Y WITH MACRON
  'ȴ' => 'l', # 0564 0234 LATIN SMALL LETTER L WITH CURL
  'ȵ' => 'n', # 0565 0235 LATIN SMALL LETTER N WITH CURL
  'ȶ' => 't', # 0566 0236 LATIN SMALL LETTER T WITH CURL
  'ɓ' => 'b', # 0595 0253 LATIN SMALL LETTER B WITH HOOK
  'ɕ' => 'c', # 0597 0255 LATIN SMALL LETTER C WITH CURL
  'ɖ' => 'd', # 0598 0256 LATIN SMALL LETTER D WITH TAIL
  'ɗ' => 'd', # 0599 0257 LATIN SMALL LETTER D WITH HOOK
  'ɠ' => 'g', # 0608 0260 LATIN SMALL LETTER G WITH HOOK
  'ɦ' => 'h', # 0614 0266 LATIN SMALL LETTER H WITH HOOK
  'ɨ' => 'i', # 0616 0268 LATIN SMALL LETTER I WITH STROKE
  'ɫ' => 'l', # 0619 026B LATIN SMALL LETTER L WITH MIDDLE TILDE
  'ɬ' => 'l', # 0620 026C LATIN SMALL LETTER L WITH BELT
  'ɭ' => 'l', # 0621 026D LATIN SMALL LETTER L WITH RETROFLEX HOOK
  'ɱ' => 'm', # 0625 0271 LATIN SMALL LETTER M WITH HOOK
  'ɲ' => 'n', # 0626 0272 LATIN SMALL LETTER N WITH LEFT HOOK
  'ɳ' => 'n', # 0627 0273 LATIN SMALL LETTER N WITH RETROFLEX HOOK
  'ɼ' => 'r', # 0636 027C LATIN SMALL LETTER R WITH LONG LEG
  'ɽ' => 'r', # 0637 027D LATIN SMALL LETTER R WITH TAIL
  'ɾ' => 'r', # 0638 027E LATIN SMALL LETTER R WITH FISHHOOK
  'ʂ' => 's', # 0642 0282 LATIN SMALL LETTER S WITH HOOK
  'ʈ' => 't', # 0648 0288 LATIN SMALL LETTER T WITH RETROFLEX HOOK
  'ʋ' => 'v', # 0651 028B LATIN SMALL LETTER V WITH HOOK
  'ʐ' => 'z', # 0656 0290 LATIN SMALL LETTER Z WITH RETROFLEX HOOK
  'ʑ' => 'z', # 0657 0291 LATIN SMALL LETTER Z WITH CURL
  'ʝ' => 'j', # 0669 029D LATIN SMALL LETTER J WITH CROSSED-TAIL
  'ʠ' => 'q', # 0672 02A0 LATIN SMALL LETTER Q WITH HOOK
  'ᵫ' => 'ue', # 7531 1D6B LATIN SMALL LETTER UE
  'Ḁ' => 'A', # 7680 1E00 LATIN CAPITAL LETTER A WITH RING BELOW
  'ḁ' => 'a', # 7681 1E01 LATIN SMALL LETTER A WITH RING BELOW
  'Ḃ' => 'B', # 7682 1E02 LATIN CAPITAL LETTER B WITH DOT ABOVE
  'ḃ' => 'b', # 7683 1E03 LATIN SMALL LETTER B WITH DOT ABOVE
  'Ḅ' => 'B', # 7684 1E04 LATIN CAPITAL LETTER B WITH DOT BELOW
  'ḅ' => 'b', # 7685 1E05 LATIN SMALL LETTER B WITH DOT BELOW
  'Ḇ' => 'B', # 7686 1E06 LATIN CAPITAL LETTER B WITH LINE BELOW
  'ḇ' => 'b', # 7687 1E07 LATIN SMALL LETTER B WITH LINE BELOW
  'Ḉ' => 'C', # 7688 1E08 LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
  'ḉ' => 'c', # 7689 1E09 LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
  'Ḋ' => 'D', # 7690 1E0A LATIN CAPITAL LETTER D WITH DOT ABOVE
  'ḋ' => 'd', # 7691 1E0B LATIN SMALL LETTER D WITH DOT ABOVE
  'Ḍ' => 'D', # 7692 1E0C LATIN CAPITAL LETTER D WITH DOT BELOW
  'ḍ' => 'd', # 7693 1E0D LATIN SMALL LETTER D WITH DOT BELOW
  'Ḏ' => 'D', # 7694 1E0E LATIN CAPITAL LETTER D WITH LINE BELOW
  'ḏ' => 'd', # 7695 1E0F LATIN SMALL LETTER D WITH LINE BELOW
  'Ḑ' => 'D', # 7696 1E10 LATIN CAPITAL LETTER D WITH CEDILLA
  'ḑ' => 'd', # 7697 1E11 LATIN SMALL LETTER D WITH CEDILLA
  'Ḓ' => 'D', # 7698 1E12 LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
  'ḓ' => 'd', # 7699 1E13 LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
  'Ḕ' => 'E', # 7700 1E14 LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
  'ḕ' => 'e', # 7701 1E15 LATIN SMALL LETTER E WITH MACRON AND GRAVE
  'Ḗ' => 'E', # 7702 1E16 LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
  'ḗ' => 'e', # 7703 1E17 LATIN SMALL LETTER E WITH MACRON AND ACUTE
  'Ḙ' => 'E', # 7704 1E18 LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
  'ḙ' => 'e', # 7705 1E19 LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
  'Ḛ' => 'E', # 7706 1E1A LATIN CAPITAL LETTER E WITH TILDE BELOW
  'ḛ' => 'e', # 7707 1E1B LATIN SMALL LETTER E WITH TILDE BELOW
  'Ḝ' => 'E', # 7708 1E1C LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
  'ḝ' => 'e', # 7709 1E1D LATIN SMALL LETTER E WITH CEDILLA AND BREVE
  'Ḟ' => 'F', # 7710 1E1E LATIN CAPITAL LETTER F WITH DOT ABOVE
  'ḟ' => 'f', # 7711 1E1F LATIN SMALL LETTER F WITH DOT ABOVE
  'Ḡ' => 'G', # 7712 1E20 LATIN CAPITAL LETTER G WITH MACRON
  'ḡ' => 'g', # 7713 1E21 LATIN SMALL LETTER G WITH MACRON
  'Ḣ' => 'H', # 7714 1E22 LATIN CAPITAL LETTER H WITH DOT ABOVE
  'ḣ' => 'h', # 7715 1E23 LATIN SMALL LETTER H WITH DOT ABOVE
  'Ḥ' => 'H', # 7716 1E24 LATIN CAPITAL LETTER H WITH DOT BELOW
  'ḥ' => 'h', # 7717 1E25 LATIN SMALL LETTER H WITH DOT BELOW
  'Ḧ' => 'H', # 7718 1E26 LATIN CAPITAL LETTER H WITH DIAERESIS
  'ḧ' => 'h', # 7719 1E27 LATIN SMALL LETTER H WITH DIAERESIS
  'Ḩ' => 'H', # 7720 1E28 LATIN CAPITAL LETTER H WITH CEDILLA
  'ḩ' => 'h', # 7721 1E29 LATIN SMALL LETTER H WITH CEDILLA
  'Ḫ' => 'H', # 7722 1E2A LATIN CAPITAL LETTER H WITH BREVE BELOW
  'ḫ' => 'h', # 7723 1E2B LATIN SMALL LETTER H WITH BREVE BELOW
  'Ḭ' => 'I', # 7724 1E2C LATIN CAPITAL LETTER I WITH TILDE BELOW
  'ḭ' => 'i', # 7725 1E2D LATIN SMALL LETTER I WITH TILDE BELOW
  'Ḯ' => 'I', # 7726 1E2E LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
  'ḯ' => 'i', # 7727 1E2F LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
  'Ḱ' => 'K', # 7728 1E30 LATIN CAPITAL LETTER K WITH ACUTE
  'ḱ' => 'k', # 7729 1E31 LATIN SMALL LETTER K WITH ACUTE
  'Ḳ' => 'K', # 7730 1E32 LATIN CAPITAL LETTER K WITH DOT BELOW
  'ḳ' => 'k', # 7731 1E33 LATIN SMALL LETTER K WITH DOT BELOW
  'Ḵ' => 'K', # 7732 1E34 LATIN CAPITAL LETTER K WITH LINE BELOW
  'ḵ' => 'k', # 7733 1E35 LATIN SMALL LETTER K WITH LINE BELOW
  'Ḷ' => 'L', # 7734 1E36 LATIN CAPITAL LETTER L WITH DOT BELOW
  'ḷ' => 'l', # 7735 1E37 LATIN SMALL LETTER L WITH DOT BELOW
  'Ḹ' => 'L', # 7736 1E38 LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
  'ḹ' => 'l', # 7737 1E39 LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
  'Ḻ' => 'L', # 7738 1E3A LATIN CAPITAL LETTER L WITH LINE BELOW
  'ḻ' => 'l', # 7739 1E3B LATIN SMALL LETTER L WITH LINE BELOW
  'Ḽ' => 'L', # 7740 1E3C LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
  'ḽ' => 'l', # 7741 1E3D LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
  'Ḿ' => 'M', # 7742 1E3E LATIN CAPITAL LETTER M WITH ACUTE
  'ḿ' => 'm', # 7743 1E3F LATIN SMALL LETTER M WITH ACUTE
  'Ṁ' => 'M', # 7744 1E40 LATIN CAPITAL LETTER M WITH DOT ABOVE
  'ṁ' => 'm', # 7745 1E41 LATIN SMALL LETTER M WITH DOT ABOVE
  'Ṃ' => 'M', # 7746 1E42 LATIN CAPITAL LETTER M WITH DOT BELOW
  'ṃ' => 'm', # 7747 1E43 LATIN SMALL LETTER M WITH DOT BELOW
  'Ṅ' => 'N', # 7748 1E44 LATIN CAPITAL LETTER N WITH DOT ABOVE
  'ṅ' => 'n', # 7749 1E45 LATIN SMALL LETTER N WITH DOT ABOVE
  'Ṇ' => 'N', # 7750 1E46 LATIN CAPITAL LETTER N WITH DOT BELOW
  'ṇ' => 'n', # 7751 1E47 LATIN SMALL LETTER N WITH DOT BELOW
  'Ṉ' => 'N', # 7752 1E48 LATIN CAPITAL LETTER N WITH LINE BELOW
  'ṉ' => 'n', # 7753 1E49 LATIN SMALL LETTER N WITH LINE BELOW
  'Ṋ' => 'N', # 7754 1E4A LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
  'ṋ' => 'n', # 7755 1E4B LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
  'Ṍ' => 'O', # 7756 1E4C LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
  'ṍ' => 'o', # 7757 1E4D LATIN SMALL LETTER O WITH TILDE AND ACUTE
  'Ṏ' => 'O', # 7758 1E4E LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
  'ṏ' => 'o', # 7759 1E4F LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
  'Ṑ' => 'O', # 7760 1E50 LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
  'ṑ' => 'o', # 7761 1E51 LATIN SMALL LETTER O WITH MACRON AND GRAVE
  'Ṓ' => 'O', # 7762 1E52 LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
  'ṓ' => 'o', # 7763 1E53 LATIN SMALL LETTER O WITH MACRON AND ACUTE
  'Ṕ' => 'P', # 7764 1E54 LATIN CAPITAL LETTER P WITH ACUTE
  'ṕ' => 'p', # 7765 1E55 LATIN SMALL LETTER P WITH ACUTE
  'Ṗ' => 'P', # 7766 1E56 LATIN CAPITAL LETTER P WITH DOT ABOVE
  'ṗ' => 'p', # 7767 1E57 LATIN SMALL LETTER P WITH DOT ABOVE
  'Ṙ' => 'R', # 7768 1E58 LATIN CAPITAL LETTER R WITH DOT ABOVE
  'ṙ' => 'r', # 7769 1E59 LATIN SMALL LETTER R WITH DOT ABOVE
  'Ṛ' => 'R', # 7770 1E5A LATIN CAPITAL LETTER R WITH DOT BELOW
  'ṛ' => 'r', # 7771 1E5B LATIN SMALL LETTER R WITH DOT BELOW
  'Ṝ' => 'R', # 7772 1E5C LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
  'ṝ' => 'r', # 7773 1E5D LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
  'Ṟ' => 'R', # 7774 1E5E LATIN CAPITAL LETTER R WITH LINE BELOW
  'ṟ' => 'r', # 7775 1E5F LATIN SMALL LETTER R WITH LINE BELOW
  'Ṡ' => 'S', # 7776 1E60 LATIN CAPITAL LETTER S WITH DOT ABOVE
  'ṡ' => 's', # 7777 1E61 LATIN SMALL LETTER S WITH DOT ABOVE
  'Ṣ' => 'S', # 7778 1E62 LATIN CAPITAL LETTER S WITH DOT BELOW
  'ṣ' => 's', # 7779 1E63 LATIN SMALL LETTER S WITH DOT BELOW
  'Ṥ' => 'S', # 7780 1E64 LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
  'ṥ' => 's', # 7781 1E65 LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
  'Ṧ' => 'S', # 7782 1E66 LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
  'ṧ' => 's', # 7783 1E67 LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
  'Ṩ' => 'S', # 7784 1E68 LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
  'ṩ' => 's', # 7785 1E69 LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
  'Ṫ' => 'T', # 7786 1E6A LATIN CAPITAL LETTER T WITH DOT ABOVE
  'ṫ' => 't', # 7787 1E6B LATIN SMALL LETTER T WITH DOT ABOVE
  'Ṭ' => 'T', # 7788 1E6C LATIN CAPITAL LETTER T WITH DOT BELOW
  'ṭ' => 't', # 7789 1E6D LATIN SMALL LETTER T WITH DOT BELOW
  'Ṯ' => 'T', # 7790 1E6E LATIN CAPITAL LETTER T WITH LINE BELOW
  'ṯ' => 't', # 7791 1E6F LATIN SMALL LETTER T WITH LINE BELOW
  'Ṱ' => 'T', # 7792 1E70 LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
  'ṱ' => 't', # 7793 1E71 LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
  'Ṳ' => 'U', # 7794 1E72 LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
  'ṳ' => 'u', # 7795 1E73 LATIN SMALL LETTER U WITH DIAERESIS BELOW
  'Ṵ' => 'U', # 7796 1E74 LATIN CAPITAL LETTER U WITH TILDE BELOW
  'ṵ' => 'u', # 7797 1E75 LATIN SMALL LETTER U WITH TILDE BELOW
  'Ṷ' => 'U', # 7798 1E76 LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
  'ṷ' => 'u', # 7799 1E77 LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
  'Ṹ' => 'U', # 7800 1E78 LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
  'ṹ' => 'u', # 7801 1E79 LATIN SMALL LETTER U WITH TILDE AND ACUTE
  'Ṻ' => 'U', # 7802 1E7A LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
  'ṻ' => 'u', # 7803 1E7B LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
  'Ṽ' => 'V', # 7804 1E7C LATIN CAPITAL LETTER V WITH TILDE
  'ṽ' => 'v', # 7805 1E7D LATIN SMALL LETTER V WITH TILDE
  'Ṿ' => 'V', # 7806 1E7E LATIN CAPITAL LETTER V WITH DOT BELOW
  'ṿ' => 'v', # 7807 1E7F LATIN SMALL LETTER V WITH DOT BELOW
  'Ẁ' => 'W', # 7808 1E80 LATIN CAPITAL LETTER W WITH GRAVE
  'ẁ' => 'w', # 7809 1E81 LATIN SMALL LETTER W WITH GRAVE
  'Ẃ' => 'W', # 7810 1E82 LATIN CAPITAL LETTER W WITH ACUTE
  'ẃ' => 'w', # 7811 1E83 LATIN SMALL LETTER W WITH ACUTE
  'Ẅ' => 'W', # 7812 1E84 LATIN CAPITAL LETTER W WITH DIAERESIS
  'ẅ' => 'w', # 7813 1E85 LATIN SMALL LETTER W WITH DIAERESIS
  'Ẇ' => 'W', # 7814 1E86 LATIN CAPITAL LETTER W WITH DOT ABOVE
  'ẇ' => 'w', # 7815 1E87 LATIN SMALL LETTER W WITH DOT ABOVE
  'Ẉ' => 'W', # 7816 1E88 LATIN CAPITAL LETTER W WITH DOT BELOW
  'ẉ' => 'w', # 7817 1E89 LATIN SMALL LETTER W WITH DOT BELOW
  'Ẋ' => 'X', # 7818 1E8A LATIN CAPITAL LETTER X WITH DOT ABOVE
  'ẋ' => 'x', # 7819 1E8B LATIN SMALL LETTER X WITH DOT ABOVE
  'Ẍ' => 'X', # 7820 1E8C LATIN CAPITAL LETTER X WITH DIAERESIS
  'ẍ' => 'x', # 7821 1E8D LATIN SMALL LETTER X WITH DIAERESIS
  'Ẏ' => 'Y', # 7822 1E8E LATIN CAPITAL LETTER Y WITH DOT ABOVE
  'ẏ' => 'y', # 7823 1E8F LATIN SMALL LETTER Y WITH DOT ABOVE
  'Ẑ' => 'Z', # 7824 1E90 LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
  'ẑ' => 'z', # 7825 1E91 LATIN SMALL LETTER Z WITH CIRCUMFLEX
  'Ẓ' => 'Z', # 7826 1E92 LATIN CAPITAL LETTER Z WITH DOT BELOW
  'ẓ' => 'z', # 7827 1E93 LATIN SMALL LETTER Z WITH DOT BELOW
  'Ẕ' => 'Z', # 7828 1E94 LATIN CAPITAL LETTER Z WITH LINE BELOW
  'ẕ' => 'z', # 7829 1E95 LATIN SMALL LETTER Z WITH LINE BELOW
  'ẖ' => 'h', # 7830 1E96 LATIN SMALL LETTER H WITH LINE BELOW
  'ẗ' => 't', # 7831 1E97 LATIN SMALL LETTER T WITH DIAERESIS
  'ẘ' => 'w', # 7832 1E98 LATIN SMALL LETTER W WITH RING ABOVE
  'ẙ' => 'y', # 7833 1E99 LATIN SMALL LETTER Y WITH RING ABOVE
  'ẚ' => 'a', # 7834 1E9A LATIN SMALL LETTER A WITH RIGHT HALF RING
  'Ạ' => 'A', # 7840 1EA0 LATIN CAPITAL LETTER A WITH DOT BELOW
  'ạ' => 'a', # 7841 1EA1 LATIN SMALL LETTER A WITH DOT BELOW
  'Ả' => 'A', # 7842 1EA2 LATIN CAPITAL LETTER A WITH HOOK ABOVE
  'ả' => 'a', # 7843 1EA3 LATIN SMALL LETTER A WITH HOOK ABOVE
  'Ấ' => 'A', # 7844 1EA4 LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
  'ấ' => 'a', # 7845 1EA5 LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
  'Ầ' => 'A', # 7846 1EA6 LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
  'ầ' => 'a', # 7847 1EA7 LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
  'Ẩ' => 'A', # 7848 1EA8 LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
  'ẩ' => 'a', # 7849 1EA9 LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
  'Ẫ' => 'A', # 7850 1EAA LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
  'ẫ' => 'a', # 7851 1EAB LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
  'Ậ' => 'A', # 7852 1EAC LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
  'ậ' => 'a', # 7853 1EAD LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
  'Ắ' => 'A', # 7854 1EAE LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
  'ắ' => 'a', # 7855 1EAF LATIN SMALL LETTER A WITH BREVE AND ACUTE
  'Ằ' => 'A', # 7856 1EB0 LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
  'ằ' => 'a', # 7857 1EB1 LATIN SMALL LETTER A WITH BREVE AND GRAVE
  'Ẳ' => 'A', # 7858 1EB2 LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
  'ẳ' => 'a', # 7859 1EB3 LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
  'Ẵ' => 'A', # 7860 1EB4 LATIN CAPITAL LETTER A WITH BREVE AND TILDE
  'ẵ' => 'a', # 7861 1EB5 LATIN SMALL LETTER A WITH BREVE AND TILDE
  'Ặ' => 'A', # 7862 1EB6 LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
  'ặ' => 'a', # 7863 1EB7 LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
  'Ẹ' => 'E', # 7864 1EB8 LATIN CAPITAL LETTER E WITH DOT BELOW
  'ẹ' => 'e', # 7865 1EB9 LATIN SMALL LETTER E WITH DOT BELOW
  'Ẻ' => 'E', # 7866 1EBA LATIN CAPITAL LETTER E WITH HOOK ABOVE
  'ẻ' => 'e', # 7867 1EBB LATIN SMALL LETTER E WITH HOOK ABOVE
  'Ẽ' => 'E', # 7868 1EBC LATIN CAPITAL LETTER E WITH TILDE
  'ẽ' => 'e', # 7869 1EBD LATIN SMALL LETTER E WITH TILDE
  'Ế' => 'E', # 7870 1EBE LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
  'ế' => 'e', # 7871 1EBF LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
  'Ề' => 'E', # 7872 1EC0 LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
  'ề' => 'e', # 7873 1EC1 LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
  'Ể' => 'E', # 7874 1EC2 LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
  'ể' => 'e', # 7875 1EC3 LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
  'Ễ' => 'E', # 7876 1EC4 LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
  'ễ' => 'e', # 7877 1EC5 LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
  'Ệ' => 'E', # 7878 1EC6 LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
  'ệ' => 'e', # 7879 1EC7 LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
  'Ỉ' => 'I', # 7880 1EC8 LATIN CAPITAL LETTER I WITH HOOK ABOVE
  'ỉ' => 'i', # 7881 1EC9 LATIN SMALL LETTER I WITH HOOK ABOVE
  'Ị' => 'I', # 7882 1ECA LATIN CAPITAL LETTER I WITH DOT BELOW
  'ị' => 'i', # 7883 1ECB LATIN SMALL LETTER I WITH DOT BELOW
  'Ọ' => 'O', # 7884 1ECC LATIN CAPITAL LETTER O WITH DOT BELOW
  'ọ' => 'o', # 7885 1ECD LATIN SMALL LETTER O WITH DOT BELOW
  'Ỏ' => 'O', # 7886 1ECE LATIN CAPITAL LETTER O WITH HOOK ABOVE
  'ỏ' => 'o', # 7887 1ECF LATIN SMALL LETTER O WITH HOOK ABOVE
  'Ố' => 'O', # 7888 1ED0 LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
  'ố' => 'o', # 7889 1ED1 LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
  'Ồ' => 'O', # 7890 1ED2 LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
  'ồ' => 'o', # 7891 1ED3 LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
  'Ổ' => 'O', # 7892 1ED4 LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
  'ổ' => 'o', # 7893 1ED5 LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
  'Ỗ' => 'O', # 7894 1ED6 LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
  'ỗ' => 'o', # 7895 1ED7 LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
  'Ộ' => 'O', # 7896 1ED8 LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
  'ộ' => 'o', # 7897 1ED9 LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
  'Ớ' => 'O', # 7898 1EDA LATIN CAPITAL LETTER O WITH HORN AND ACUTE
  'ớ' => 'o', # 7899 1EDB LATIN SMALL LETTER O WITH HORN AND ACUTE
  'Ờ' => 'O', # 7900 1EDC LATIN CAPITAL LETTER O WITH HORN AND GRAVE
  'ờ' => 'o', # 7901 1EDD LATIN SMALL LETTER O WITH HORN AND GRAVE
  'Ở' => 'O', # 7902 1EDE LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
  'ở' => 'o', # 7903 1EDF LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
  'Ỡ' => 'O', # 7904 1EE0 LATIN CAPITAL LETTER O WITH HORN AND TILDE
  'ỡ' => 'o', # 7905 1EE1 LATIN SMALL LETTER O WITH HORN AND TILDE
  'Ợ' => 'O', # 7906 1EE2 LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
  'ợ' => 'o', # 7907 1EE3 LATIN SMALL LETTER O WITH HORN AND DOT BELOW
  'Ụ' => 'U', # 7908 1EE4 LATIN CAPITAL LETTER U WITH DOT BELOW
  'ụ' => 'u', # 7909 1EE5 LATIN SMALL LETTER U WITH DOT BELOW
  'Ủ' => 'U', # 7910 1EE6 LATIN CAPITAL LETTER U WITH HOOK ABOVE
  'ủ' => 'u', # 7911 1EE7 LATIN SMALL LETTER U WITH HOOK ABOVE
  'Ứ' => 'U', # 7912 1EE8 LATIN CAPITAL LETTER U WITH HORN AND ACUTE
  'ứ' => 'u', # 7913 1EE9 LATIN SMALL LETTER U WITH HORN AND ACUTE
  'Ừ' => 'U', # 7914 1EEA LATIN CAPITAL LETTER U WITH HORN AND GRAVE
  'ừ' => 'u', # 7915 1EEB LATIN SMALL LETTER U WITH HORN AND GRAVE
  'Ử' => 'U', # 7916 1EEC LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
  'ử' => 'u', # 7917 1EED LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
  'Ữ' => 'U', # 7918 1EEE LATIN CAPITAL LETTER U WITH HORN AND TILDE
  'ữ' => 'u', # 7919 1EEF LATIN SMALL LETTER U WITH HORN AND TILDE
  'Ự' => 'U', # 7920 1EF0 LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
  'ự' => 'u', # 7921 1EF1 LATIN SMALL LETTER U WITH HORN AND DOT BELOW
  'Ỳ' => 'Y', # 7922 1EF2 LATIN CAPITAL LETTER Y WITH GRAVE
  'ỳ' => 'y', # 7923 1EF3 LATIN SMALL LETTER Y WITH GRAVE
  'Ỵ' => 'Y', # 7924 1EF4 LATIN CAPITAL LETTER Y WITH DOT BELOW
  'ỵ' => 'y', # 7925 1EF5 LATIN SMALL LETTER Y WITH DOT BELOW
  'Ỷ' => 'Y', # 7926 1EF6 LATIN CAPITAL LETTER Y WITH HOOK ABOVE
  'ỷ' => 'y', # 7927 1EF7 LATIN SMALL LETTER Y WITH HOOK ABOVE
  'Ỹ' => 'Y', # 7928 1EF8 LATIN CAPITAL LETTER Y WITH TILDE
  'ỹ' => 'y', # 7929 1EF9 LATIN SMALL LETTER Y WITH TILDE
);

#####################################################################
#METHODS
#####################################################################

sub new {
  my $class = shift;
  my $self =  {
	      };
  bless ($self, $class);
  &_initialize($self);
  return $self;
}# end of new();

sub _initialize {
  #
  # initialize the toCaronized hash
  #
  foreach my $ord (128 .. 35565) {
    #my $ord = ord($c);
    my $codepoint = sprintf("%04X", $ord);
    my $charinfo = charinfo($codepoint);
    my %charinfo = %$charinfo;
    #warn "CHARINFO \[$charinfo\]\n";
    #code             code point with at least four hexdigits
    #name             name of the character IN UPPER CASE
    #category         general category of the character
    #combining        classes used in the Canonical Ordering Algorithm
    #bidi             bidirectional category
    #decomposition    character decomposition mapping
    #decimal          if decimal digit this is the integer numeric value
    #digit            if digit this is the numeric value
    #numeric          if numeric is the integer or rational numeric value
    #mirrored         if mirrored in bidirectional text
    #unicode10        Unicode 1.0 name if existed and different
    #comment          ISO 10646 comment field
    #upper            uppercase equivalent mapping
    #lower            lowercase equivalent mapping
    #title            titlecase equivalent mapping
    my $name = $charinfo{name};
    my $decomposition = $charinfo{decomposition};
    my ($toBeModified, $modifier) = split(/\s+/, $decomposition, 2);
    if ($modifier eq "030C") {	# if foo WITH CARON
      my $rawLetter = chr(hex($toBeModified));
      my $caronizedLetter = chr(hex($codepoint));
      #warn "MODIFYING $toBeModified \[$rawLetter\] by $modifier TO FORM \[$caronizedLetter\] $name\n";
      $toCaronized{$rawLetter} = $caronizedLetter;
    }
  }# each of the lowest buncha codepoints
}# end of _initialize

	

# 2006_09_24 -- entities2UTF8
# adapted from HTML::Entities; conversions to values above ff are allowed.
sub entities2UTF8
{
    my $array;
    if (defined wantarray) {
	$array = [@_]; # copy
    } else {
	$array = \@_;  # modify in-place
    }
    my $c;
    for (@$array) {
      #s/(&\#(\d+);?)/$2 < 256 ? chr($2) : $1/eg;
      #s/(&\#[xX]([0-9a-fA-F]+);?)/$c = hex($2); $c < 256 ? chr($c) : $1/eg;
      #s/(&(\w+);?)/$HTML::Entities::entity2char{$2} || $1/eg;
      s/(&\#(\d+);?)/chr($2)/eg;
      s/(&\#[xX]([0-9a-fA-F]+);?)/chr(hex($2))/eg;
      #2006_11_26 -- maybe special treatment for &nbsp; or it disappears
      s/(&(\w+);?)/$HTML::Entities::entity2char{$2} || $1/eg;
    }
    wantarray ? @$array : $array->[0];
}# end of entities2UTF8()

#$safeString = toLatinSafe($string);
#2007_05_28 -- make allowing punctuation optional
#my $safeName = FFUTF::toLatinSafe($name[, "ALLOW_PUNCTUATION"]);
sub toLatinSafe {
  my ($string, $allowPunctuationFlag) = @_;

  #warn "TO_LATIN_SAFE BEGIN \[$string\] \[$allowPunctuationFlag\]\n";
  my @retString = ();
  foreach my $c (split(//, $string)) {
    my $replacement = "";
    if ($c =~ /\p{isAlnum}/) {	# if Ll Lu Lt Lo Nd
      if ($c =~ /[A-Za-z0-9]/) {	# normal Latin letter or number
	#warn "TO_LATIN_SAFE NOT COMPLICATED \[$c\]\n";
	$replacement .= $c;		# replace as-is
      }
      else {	# look it up in our uncode array
	#warn "TO_LATIN_SAFE IS COMPLICATED \[$c\]\n";
	if (defined $decoratedLatinToFlat{$c} ) {
          my $basechar = $decoratedLatinToFlat{$c};
	  $replacement .= $basechar;
	} else {
	  #
	  # no charinfo!
	  # 
	  #warn "NO CHARINFO! \[$c\]\n";
	}
      }# original char is or is not simple latin alphanumeric
    }# original char is alphanumeric
    elsif ($allowPunctuationFlag) {	# e.g. period or hyphen or nbsp
      #2007_05_27 -- allow - and . - etc.  for map2xml.pl
      #warn "TO_LATIN_SAFE ALLOWS PUNCTUATION FLAG \[$c\]\n";
      $replacement .= $c;		# replace as-is
    }
    $replacement = " " if ($replacement =~ /^$/); # default: replace with space
    if ($replacement =~ /../) {
      #warn "FFUTF Made a COMPLEX REPLACEMENT: \[$c\] -> \[$replacement\]\n";
    }
    #warn "TO_LATIN_SAFE PUSHING REPLACEMENT \[$replacement\]\n";
    push(@retString, $replacement);
  }# each char in string

  #warn "TO_LATIN_SAFE END \[$string\] \[$allowPunctuationFlag\]\n";
  return join("", @retString);

}# end of toLatinSafe();

#my $combinedLetter = FFUTFOjject->addCaron($toBeModified);
sub addCaron {
  my ($self, $toBeModified) = @_;	# the plain latin letter to be modified
  my $ret = $toBeModified;	# default is plain letter if no caronized avail
  $ret = $toCaronized{$toBeModified} if $toCaronized{$toBeModified};

  return ($ret);

}# end of addCaron();

#2007_05_27 -- add basic idiomatic flatLatin -- oe, ae, etc.
sub toIdiomaticLatinSafe {
  my $s = shift();
  #2011_09_01 -- RETURN IF LIKELY NO UNFLAT LATIN TO CONVERT
  return ($s) if ($s =~ m%^[A-Za-z0-9_ .&'",/-]*$%);	#"'
  
  $s =~ s/Ä/AE/g;
  $s =~ s/ä/ae/g;
  $s =~ s/Ö/OE/g;
  $s =~ s/ö/oe/g;
  $s =~ s/Ü/UE/g;
  $s =~ s/ü/ue/g;
  return toLatinSafe($s, "ALLOW_PUNCTUATION");
}

#2014_07_17 -- routine to convert all entities to utf-8, then return flat latin
#my $flatLatinNoEntities = FFUTF::flatLatinNoEntities($input);
sub flatLatinNoEntities {
	my ($in) = @_;
	my $flatLatinNoEntities = ();
		while ($in =~ s/(&.)([A-Z]+);/$1_GORGO_;/) {
		my $lc = lc($2);
		$in =~ s/_GORGO_/$lc/;
	}

	if ($in =~ /&.[a-z]+;/) {
		$in =~ s/ &([,; ])/ &amp;$1 /g;
		$in =~ s/&Scaron;/Š/g;
		$in =~ s/&scaron;/š/g;
		$in =~ s/&rsquo;/’/ig;
		$in =~ s/&lsquo;/‘/ig;
		$in =~ s/&rdquo;/”/ig;
		$in =~ s/&ldquo;/“/ig;
		$in =~ s/&nbsp;/ /ig;
		$in =~ s/&hellip;/…/ig;
		$in =~ s/&ndash;/—/ig;
		$in =~ s/&mdash;/–/ig;
		$in =~ s/&bull;/•/ig;
		$in = FFUTF::entities2UTF8($in);
	}

	return $in;

}# end of &flatLatinNoEntities($input);
###################### END OF MODULE ##########################
1
